#!/bin/bash
# Multiple shebangs are fine :-)

# error function checks?

dbg(){
	if ! $DEBUG; then
		>&2 echo "$1"
	fi
}

err(){
	if ! $QUIET; then
		>&2 echo "$1"
	fi
}

usage(){
	if ! $QUIET; then
		>&2 echo "Usage: BLANK"
	fi
}

