#!/bin/bash
# this is literally terrible work
dbg(){
	>&2 echo $1
}
dbg "Contate running on ${1}! (this is stderr)"
THIS=''
declare -A CONTATORS 
while read -r line || [[ -n "$line" ]]; do
	if	[[ "$line" == *"<!-- contate:"* ]]; then
		TEMPLATE_FILE=$(echo $line | cut -d':' -f 2)
		EXPR_STR=$(echo $line | cut -d':' -f 3)
		TEMPLATE_VARIABLE=$(echo $EXPR_STR | cut -d'=' -f 1)
		CONTENT_VALUE=$(echo $EXPR_STR | cut -d'=' -f 2)
		CONTATORS["$TEMPLATE_VARIABLE"]="$CONTENT_VALUE"
	else
		THIS+="${line}\n"
	fi
done < "$1"
OHTML=''
while read -r line || [[ -n "$line" ]]; do
	if [[ "$line" == *"<!-- @"* ]]; then
		FIXED_LINE=''
		TEMPLATE_VAR=$(echo $line | cut -d'@' -f 2)
		CONTENT_VAL=${CONTATORS["${TEMPLATE_VAR}"]}
		FIXED_LINE=$(echo $line | awk -F '<!-- @' '{$0=$1}1')
		if [[ "$CONTENT_VAL" == '"'*'"' ]]; then
			INSERTER=${CONTENT_VAL#*'"'}
			INSERTER=${INSERTER%'"'*}
		else
			case $CONTENT_VAL in
				this) #build in function, i guess. stupid way of doing this
					INSERTER=${THIS}
					;;
				*)
					dbg "running ${CONTENT_VAL}!"
					INSERTER=`exec "./bin.contate/${CONTENT_VAL}"`
					;;
			esac
		fi
		FIXED_LINE+=${INSERTER}
		FIXED_LINE+=$(echo $line | awk -F '@ -->' '{$0=$2}1')
		OHTML+="${FIXED_LINE}\n"
	else
		OHTML+="${line}\n"
	fi
done < "./templates.contate/${TEMPLATE_FILE}"
echo -e $OHTML
